# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'
services:

  comapiadmin:
    container_name: com.api.admin
    image: fengma312/com.api.admin:latest
    build:
      context: .
      dockerfile: Com.Api/Com.Api.Admin/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=home

  comapiopen:
    container_name: com.api.open
    image: fengma312/com.api.open:latest
    build:
      context: .
      dockerfile: Com.Api/Com.Api.Open/Dockerfile
    depends_on:
      - comapiadmin
    environment:
      - DOTNET_ENVIRONMENT=home

  comserviceAccount:
    container_name: Com.Service.Account
    image: fengma312/com.service.account:latest
    build:
      context: .
      dockerfile: Com.Service/Com.Service.Account/Dockerfile
    ports:
      - "8010:8010"
    environment:
      - DOTNET_ENVIRONMENT=home
    depends_on:
      - comapiadmin

  comserviceTrade:
    container_name: Com.Service.Trade
    image: fengma312/com.service.trade:latest
    build:
      context: .
      dockerfile: Com.Service/Com.Service.Trade/Dockerfile
    ports:
      - "8030:8030"
    environment:
      - DOTNET_ENVIRONMENT=home
    depends_on:
      - comapiadmin

  comserviceMatch:
    container_name: Com.Service.Match
    image: fengma312/com.service.match:latest
    build:
      context: .
      dockerfile: Com.Service/Com.Service.Match/Dockerfile
    ports:
      - "8020:8020"
    environment:
      - DOTNET_ENVIRONMENT=home
    depends_on:
      - comapiadmin
